/**
 * The daily research digest (src/research/dailyResearch.js): once per UTC
 * day, one low-priority call, written to state/digests/, and — above all —
 * never able to fail the pulse when every free provider is rate-limited.
 * Zero network: the registry is a fake.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, existsSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { StateStore } from '../src/state/store.js';
import {
  runDailyResearch, loadResearchTopics, pickTopics, buildResearchMessages, sanitizeDigestBody, researchEnabledFromEnv, DEFAULT_TOPICS_PATH,
} from '../src/research/dailyResearch.js';
import { parseSafetyRules } from '../src/policy/safetyRules.js';
import { runPulse } from '../src/engine/pulse.js';
import { FakeProviderAgent } from '../src/fakes/fakeProvider.js';
import { FakeGitHub } from '../src/fakes/fakeGitHub.js';

const DAY1 = new Date('2026-06-10T06:05:00.000Z');
const GOOD_BODY = [
  '## free-tier-llm-landscape', '- Limits move often.', '- An agent that only uses free tiers must re-discover models.', '- Verify current per-minute caps.',
  '## agent-safety-practice', '- Approval tiers.', '- They keep irreversible actions human-gated.', '- Verify your own audit log covers them.',
].join('\n');

function fakeRegistry({ configured = ['groq'], reply = { text: GOOD_BODY, service: 'groq', model: 'llama-test' }, failWith = null } = {}) {
  const calls = [];
  return {
    calls,
    configuredIds: () => configured,
    async chat(messages, opts) {
      calls.push({ messages, opts });
      if (failWith) throw failWith;
      return typeof reply === 'function' ? reply() : reply;
    },
  };
}
const allFailed = (failureClass) => Object.assign(new Error('All providers failed for this request (tried: groq, together)'), { code: 'ALL_PROVIDERS_FAILED', failureClass });

function world() {
  const stateDir = mkdtempSync(join(tmpdir(), 'titan-research-'));
  const store = new StateStore({ stateDir });
  store.ensureLayout();
  const events = [];
  const sink = { append: (type, data) => events.push({ type, ...data }) };
  return {
    stateDir, store, events, sink,
    digest: (date = '2026-06-10') => join(stateDir, 'digests', `${date}-research.md`),
    digests: () => (existsSync(join(stateDir, 'digests')) ? readdirSync(join(stateDir, 'digests')).filter((f) => f.endsWith('-research.md')) : []),
    state: () => JSON.parse(readFileSync(join(stateDir, 'research.json'), 'utf8')),
    view: () => JSON.parse(readFileSync(join(stateDir, 'views', 'research.json'), 'utf8')),
    cleanup: () => rmSync(stateDir, { recursive: true, force: true }),
  };
}
const run = (w, registry, over = {}) => runDailyResearch({ store: w.store, registry, now: () => DAY1, events: w.sink, control: {}, ...over });

test('writes one digest to state/digests/, labelled as model knowledge with no web access, and surfaces it in a view', async () => {
  const w = world();
  try {
    const registry = fakeRegistry();
    const r = await run(w, registry);
    assert.deepEqual([r.status, r.reason, r.file, r.provider, r.model], ['written', 'ok', 'state/digests/2026-06-10-research.md', 'groq', 'llama-test']);

    // One lightweight, LOW-priority call over the existing pool, bounded.
    assert.equal(registry.calls.length, 1);
    const { messages, opts } = registry.calls[0];
    assert.equal(opts.priority, 'low');
    assert.ok(opts.maxTokens <= 700 && opts.maxProviders <= 2);
    assert.match(messages[1].content, /Date: 2026-06-10/);
    for (const id of ['free-tier-llm-landscape', 'agent-safety-practice', 'actions-automation']) assert.ok(messages[1].content.includes(id), id);
    assert.match(messages[0].content, /no web access/);

    const text = readFileSync(w.digest(), 'utf8');
    assert.match(text, /^# Research digest — 2026-06-10/);
    assert.match(text, /Generated by TITAN-Runner at 2026-06-10T06:05:00\.000Z using groq \(llama-test\)/);
    assert.match(text, /no web access and cited no live sources/);
    assert.ok(text.includes('- Limits move often.'));

    assert.deepEqual([w.state().lastStatus, w.state().lastDigestDate, w.state().lastDigestFile], ['written', '2026-06-10', 'state/digests/2026-06-10-research.md']);
    const view = w.view();
    assert.equal(view.lastStatus, 'written');
    assert.equal(view.digest.date, '2026-06-10');
    assert.ok(view.digest.preview.includes('Limits move often'));
    assert.deepEqual(w.events.map((e) => [e.type, e.outcome]), [['research.written', 'written']]);
  } finally {
    w.cleanup();
  }
});

test('once per UTC day: a second run the same day does not call a provider; the next day writes a new digest', async () => {
  const w = world();
  try {
    const registry = fakeRegistry();
    await run(w, registry);
    const again = await run(w, registry, { now: () => new Date('2026-06-10T23:59:00.000Z') });
    assert.deepEqual([again.status, again.reason], ['skipped', 'already-written']);
    assert.equal(registry.calls.length, 1, 'no second model call');
    // Even with research.json lost, the existing digest file is what counts.
    rmSync(join(w.stateDir, 'research.json'));
    assert.equal((await run(w, registry)).reason, 'already-written');
    assert.equal(registry.calls.length, 1);

    const next = await run(w, registry, { now: () => new Date('2026-06-11T06:05:00.000Z') });
    assert.equal(next.status, 'written');
    assert.equal(registry.calls.length, 2);
    assert.deepEqual(w.digests().sort(), ['2026-06-10-research.md', '2026-06-11-research.md']);
  } finally {
    w.cleanup();
  }
});

test('every free provider rate-limited: skipped silently — no digest, no throw, recorded once, and retried only after the backoff', async () => {
  const w = world();
  try {
    const limited = fakeRegistry({ failWith: allFailed('rate_limited') });
    const r = await run(w, limited);
    assert.deepEqual([r.status, r.reason], ['skipped', 'rate_limited']);
    assert.deepEqual(w.digests(), []);
    assert.deepEqual([w.state().lastStatus, w.state().lastReason], ['skipped', 'rate_limited']);
    assert.equal(w.state().lastDigestDate, undefined);
    assert.deepEqual(w.events.map((e) => [e.type, e.reason]), [['research.skipped', 'rate_limited']]);
    assert.equal(w.view().digest, null);

    // The next pulse, 15 minutes later: backoff, no provider call.
    const soon = await run(w, limited, { now: () => new Date(DAY1.getTime() + 15 * 60_000) });
    assert.deepEqual([soon.status, soon.reason], ['skipped', 'backoff']);
    assert.equal(limited.calls.length, 1);

    // After the window (default 3h) it tries again — and succeeds once a provider recovers.
    const recovered = fakeRegistry();
    const later = await run(w, recovered, { now: () => new Date(DAY1.getTime() + 181 * 60_000) });
    assert.equal(later.status, 'written');
    assert.equal(w.state().lastStatus, 'written');
    assert.equal(w.view().digest.date, '2026-06-10');

    // A custom retry window is honoured.
    const w2 = world();
    try {
      await run(w2, limited);
      const r2 = await run(w2, fakeRegistry(), { now: () => new Date(DAY1.getTime() + 11 * 60_000), retryMinutes: 10 });
      assert.equal(r2.status, 'written');
    } finally {
      w2.cleanup();
    }
  } finally {
    w.cleanup();
  }
});

test('failures of every shape are skipped, never thrown: provider down, timeout, empty, too-short, and a registry that explodes', async () => {
  for (const [label, registry, reason] of [
    ['provider down', fakeRegistry({ failWith: allFailed('provider_down') }), 'provider_down'],
    ['no class', fakeRegistry({ failWith: Object.assign(new Error('boom'), { code: 'UPSTREAM_ERROR' }) }), 'UPSTREAM_ERROR'],
    ['plain error', fakeRegistry({ failWith: new Error('boom') }), 'provider-error'],
    ['empty text', fakeRegistry({ reply: { text: '', service: 'groq', model: 'm' } }), 'empty-response'],
    ['tiny text', fakeRegistry({ reply: { text: 'ok', service: 'groq', model: 'm' } }), 'empty-response'],
    ['null reply', fakeRegistry({ reply: null }), 'empty-response'],
    ['exploding configuredIds', { configuredIds() { throw new Error('kaboom'); }, chat: async () => { throw new Error('unreachable'); } }, 'error'],
  ]) {
    const w = world();
    try {
      const r = await run(w, registry);
      assert.deepEqual([r.status, r.reason], ['skipped', reason], label);
      assert.deepEqual(w.digests(), [], label);
    } finally {
      w.cleanup();
    }
  }
});

test('quiet skips write nothing and emit nothing: no provider configured, disabled, dry-run, kill switch, drain, autonomy dry-run, out of pulse budget', async () => {
  const cases = [
    ['no provider', fakeRegistry({ configured: [] }), {}, 'no-provider'],
    ['disabled', fakeRegistry(), { enabled: false }, 'disabled'],
    ['dry-run', fakeRegistry(), { dryRun: true }, 'dry-run'],
    ['kill switch', fakeRegistry(), { control: { killSwitch: true } }, 'kill-switch'],
    ['drain', fakeRegistry(), { control: { drain: true } }, 'drain'],
    ['autonomy dry-run', fakeRegistry(), { control: { autonomy: 'dry-run' } }, 'autonomy-dry-run'],
    ['pulse budget', fakeRegistry(), { shouldStop: () => true }, 'pulse-budget'],
    ['no topics', fakeRegistry(), { topicsConfig: { topics: [], maxTopics: 3, warnings: [] } }, 'no-topics'],
  ];
  for (const [label, registry, over, reason] of cases) {
    const w = world();
    try {
      const r = await run(w, registry, over);
      assert.deepEqual([r.status, r.reason], ['skipped', reason], label);
      assert.equal(registry.calls.length, 0, `${label}: no model call`);
      assert.equal(existsSync(join(w.stateDir, 'research.json')), false, `${label}: no state written`);
      assert.deepEqual(w.events, [], `${label}: no event`);
      assert.deepEqual(w.digests(), [], label);
    } finally {
      w.cleanup();
    }
  }
});

test('the digest is a state append: if the safety rules stop auto-approving that, research does not run', async () => {
  const w = world();
  try {
    const strict = parseSafetyRules('version: 1\nauto_approve:\n  - read\nalways_ask:\n  - state-append\n');
    const registry = fakeRegistry();
    const r = await run(w, registry, { rules: strict });
    assert.deepEqual([r.status, r.reason], ['skipped', 'safety-rules']);
    assert.equal(registry.calls.length, 0);
    // With the shipped rules it runs.
    assert.equal((await run(w, registry)).status, 'written');
  } finally {
    w.cleanup();
  }
});

test('model output is scrubbed before it reaches a public repo: credentials, emails, a wrapping code fence, and runaway length', async () => {
  const dirty = ['```markdown', '## t', '- key ghp_abcdefghijklmnopqrstuvwxyz0123456789 and mail someone@example.com', '- ok'.padEnd(200, '.'), '```'].join('\n');
  const w = world();
  try {
    await run(w, fakeRegistry({ reply: { text: dirty, service: 'groq', model: 'm' } }));
    const text = readFileSync(w.digest(), 'utf8');
    assert.ok(!text.includes('ghp_abcdefghijklmnopqrstuvwxyz0123456789'));
    assert.ok(!text.includes('someone@example.com'));
    assert.ok(!text.includes('```'));
    assert.ok(!JSON.stringify(w.view()).includes('ghp_abc'));
  } finally {
    w.cleanup();
  }
  const long = sanitizeDigestBody(`## t\n${'word '.repeat(5000)}`);
  assert.ok(long.length < 6100 && long.endsWith('_(truncated)_'));
  assert.equal(sanitizeDigestBody(undefined), '');
});

test('a later skipped attempt does not blank the last digest the dashboard shows', async () => {
  const w = world();
  try {
    await run(w, fakeRegistry());
    const tomorrow = new Date('2026-06-11T06:05:00.000Z');
    await run(w, fakeRegistry({ failWith: allFailed('rate_limited') }), { now: () => tomorrow });
    const view = w.view();
    assert.equal(view.lastStatus, 'skipped');
    assert.equal(view.lastReason, 'rate_limited');
    assert.equal(view.digest.date, '2026-06-10', 'still points at the last real digest');
    assert.ok(view.digest.preview.includes('Limits move often'));
  } finally {
    w.cleanup();
  }
});

/* -------------------------------------------------------------------------- */
/* Topics                                                                      */
/* -------------------------------------------------------------------------- */

test('the shipped topics file loads; rotation is deterministic and covers a long list over days; malformed files give no topics and a warning', () => {
  const shipped = loadResearchTopics();
  assert.deepEqual(shipped.warnings, []);
  assert.equal(shipped.source, 'config/research-topics.yml');
  assert.equal(shipped.topics.length, 3);
  assert.equal(shipped.maxTopics, 3);
  assert.ok(existsSync(DEFAULT_TOPICS_PATH));

  const five = ['a', 'b', 'c', 'd', 'e'].map((id) => ({ id, prompt: id }));
  const seen = new Set();
  for (let day = 0; day < 5; day++) {
    const picked = pickTopics(five, 2, new Date(Date.UTC(2026, 5, 10 + day)));
    assert.equal(picked.length, 2);
    picked.forEach((t) => seen.add(t.id));
    assert.deepEqual(picked, pickTopics(five, 2, new Date(Date.UTC(2026, 5, 10 + day, 23, 59))), 'same day, same topics');
  }
  assert.equal(seen.size, 5);
  assert.equal(pickTopics(five, 9, DAY1).length, 5);

  const dir = mkdtempSync(join(tmpdir(), 'titan-topics-'));
  try {
    const file = join(dir, 't.yml');
    assert.deepEqual(loadResearchTopics({ path: join(dir, 'nope.yml') }), { topics: [], maxTopics: 0, source: 'none', warnings: [] });
    for (const text of ['version: 2\n', 'version: 1\ntopics:\n  - a\n', 'version: 1\n', 'version: 1\ntopics:\n  a: [x]\n']) {
      writeFileSync(file, text);
      const r = loadResearchTopics({ path: file });
      assert.equal(r.topics.length, 0, text);
      assert.equal(r.warnings.length, 1, text);
    }
    writeFileSync(file, 'version: 1\nmax_topics: 99\ntopics:\n  ok: "fine"\n  empty: ""\n  num: 5\n');
    const partial = loadResearchTopics({ path: file });
    assert.deepEqual(partial.topics, [{ id: 'ok', prompt: 'fine' }]);
    assert.equal(partial.maxTopics, 6, 'capped');
    assert.equal(partial.warnings.length, 2);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }

  assert.match(buildResearchMessages(five.slice(0, 2), '2026-06-10')[1].content, /1\. a: a\n2\. b: b/);
  assert.equal(researchEnabledFromEnv({}), true);
  assert.equal(researchEnabledFromEnv({ TITAN_RESEARCH: '0' }), false);
  assert.equal(researchEnabledFromEnv({ TITAN_RESEARCH: '1' }), true);
});

/* -------------------------------------------------------------------------- */
/* Through the real pulse                                                      */
/* -------------------------------------------------------------------------- */

function pulseWorld() {
  const stateDir = mkdtempSync(join(tmpdir(), 'titan-research-pulse-'));
  const repoRoot = mkdtempSync(join(tmpdir(), 'titan-repo-'));
  mkdirSync(join(repoRoot, 'src'));
  const github = new FakeGitHub({ fixture: { issues: [] }, repository: 'owner-login/repo', now: () => DAY1 });
  const fake = new FakeProviderAgent({ script: { seed: 1, latencyMs: [1, 2], rules: [{ kind: '*', sequence: [{ reply: 'prose', text: 'x' }] }] }, quiet: true });
  const deps = (extra = {}) => ({ stateDir, repoRoot, github, pools: { phase2: fake }, reviewerChat: fake.chat.bind(fake), dryRun: false, now: () => DAY1, ...extra });
  return { stateDir, deps, cleanup: () => { rmSync(stateDir, { recursive: true, force: true }); rmSync(repoRoot, { recursive: true, force: true }); } };
}

test('through runPulse: the digest is written once a day, and a rate-limited day costs the pulse nothing', async () => {
  const w = pulseWorld();
  try {
    const registry = fakeRegistry();
    const a = await runPulse(w.deps({ pulseId: 'p1', research: { enabled: true, registry } }));
    assert.equal(a.error, null);
    assert.ok(existsSync(join(w.stateDir, 'digests', '2026-06-10-research.md')));
    assert.ok(existsSync(join(w.stateDir, 'views', 'research.json')));
    await runPulse(w.deps({ pulseId: 'p2', research: { enabled: true, registry } }));
    assert.equal(registry.calls.length, 1, 'the second pulse that day made no research call');

    // A fresh day where every provider is rate-limited: the pulse still succeeds, nothing new is written.
    const limited = fakeRegistry({ failWith: allFailed('rate_limited') });
    const b = await runPulse(w.deps({ pulseId: 'p3', now: () => new Date('2026-06-11T06:05:00.000Z'), research: { enabled: true, registry: limited } }));
    assert.equal(b.error, null, 'a rate-limited research pass must not fail the pulse');
    assert.equal(limited.calls.length, 1);
    assert.ok(!existsSync(join(w.stateDir, 'digests', '2026-06-11-research.md')));
    const hb = JSON.parse(readFileSync(join(w.stateDir, 'heartbeat.json'), 'utf8'));
    assert.equal(hb.lastPulseStatus, 'ok');
  } finally {
    w.cleanup();
  }
});

test('through runPulse: research stays off when fakes are injected unless a caller turns it on, and in dry-run', async () => {
  const w = pulseWorld();
  try {
    const registry = fakeRegistry();
    // deps.research.registry alone does not enable it while pools/github are injected.
    await runPulse(w.deps({ pulseId: 'p1', research: { registry } }));
    assert.equal(registry.calls.length, 0);
    await runPulse(w.deps({ pulseId: 'p2', dryRun: true, research: { enabled: true, registry } }));
    assert.equal(registry.calls.length, 0, 'dry-run makes no model call');
    await runPulse(w.deps({ pulseId: 'p3', research: { enabled: false, registry } }));
    assert.equal(registry.calls.length, 0);
    assert.equal(existsSync(join(w.stateDir, 'digests')) ? readdirSync(join(w.stateDir, 'digests')).filter((f) => f.endsWith('-research.md')).length : 0, 0);
  } finally {
    w.cleanup();
  }
});
